version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: brieflydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.2:5432/brieflydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9495:9495"

volumes:
  postgres_data: