apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-llm
  labels:
    app: fastapi-llm
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: fastapi-llm
  template:
    metadata:
      labels:
        app: fastapi-llm
    spec:
      containers:
        - name: fastapi-llm
          image: "your-repo/fastapi-llm:latest" # Adjust as needed
          ports:
            - containerPort: 80 # Adjust as needed
