replicaCount: 1
image:
  repository: edgeofsoumik/briefly-fastapi-llm
  tag: 0.0.1.RELEASE
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
env:
  - name: DB_URL
    value: "postgres://my-postgresql-0:5432/mydatabase"
  - name: DB_USERNAME
    value: "myuser"
  - name: DB_PASSWORD
    value: "mysecretpassword"
  - name: COHERE_API_KEY
    value: "230EPrtHtGFNHxcIt2gbqU4rYo3HnhVMkiS9nxSF"
resources: {}
serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80