# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgresql-init-scripts
#   namespace: database
# data:
#   init.sql: |
#     CREATE TABLE IF NOT EXISTS request_history (
#         id SERIAL PRIMARY KEY,
#         url TEXT NOT NULL,
#         summary TEXT NOT NULL,
#         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
#     );