# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-postgresql
# spec:
#   capacity:
#     storage: 8Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   hostPath:
#     path: /mnt/data  # Ensure this path exists on the Minikube node
#   persistentVolumeReclaimPolicy: Retain