# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-postgresql-0
#   namespace: database
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: standard
#   volumeName: pv-postgresql