# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql
#   namespace: database
# spec:
#   ports:
#   - port: 5432
#     targetPort: 5432
#   selector:
#     app: postgresql
#   type: ClusterIP