apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP # Adjust as needed
  ports:
    - port: 80 # Adjust as needed
      targetPort: 80 # Adjust as needed
  selector:
    app: frontend
